package easy;

/**
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.

 */
public class Problem389 {
    public char findTheDifference(String s, String t) {

        /*
        a ^ 0 = a
         */

        int xor = 0;
        for (int i = 0; i < t.length(); i++) {
            xor = xor ^ t.charAt(i);
        }
        for (int j = 0; j < s.length(); j++) {
            xor = xor ^ s.charAt(j);
        }

        return (char)xor;
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        Problem389 problem389 = new Problem389();
        char result = problem389.findTheDifference(s, t);
        System.out.println(result);
    }
}
